In [27]:
import pickle
import torch

In [44]:
torch_script = pickle.load(open('/home/henry/code/NLP/torch_script_output.pkl', 'rb'))
tensorrt = pickle.load(open('/home/henry/code/NLP/tensorrt_output_32bit.pkl', 'rb'))

In [45]:
torch_script.shape

torch.Size([7765, 2])

In [46]:
tensorrt.shape

torch.Size([7765, 2])

In [47]:
torch_script[1]

tensor([ 2.7257, -3.0739])

In [48]:
tensorrt[1]

tensor([ 2.7279, -3.0757])

In [49]:
softmax = torch.nn.Softmax(dim=-1)


In [50]:
torch_script_sf = softmax(torch_script)
rt_sf = softmax(tensorrt)

In [51]:
ts_idx = torch.argmax(torch_script_sf, dim=-1)
rt_idx = torch.argmax(rt_sf, dim=-1)

In [52]:
(ts_idx==rt_idx).sum()

tensor(7764)

In [53]:
torch_script_sf.shape

torch.Size([7765, 2])

In [54]:
import numpy as np

In [55]:
torch.from_numpy(np.array([1,0,1])).bool()

tensor([ True, False,  True])